### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by engrdanish** [wt-io-it/odoo-pycharm-plugin#29]
Plugin Version: 0.5.12
IDEA Version: PyCharm 2022.1.1

<details><summary>java.lang.StackOverflowError</summary>

```
Please copy the stacktrace/file to the issue manually (the text is too big to post in a link)
```
</details>

**Comment by ap-wtioit** [comment]
@engrdanish do you still have the stacktrace in your logs and could you paste it into the issue?

**Comment by engrdanish** [comment]
I don't know it gave me some IDE Error and sometime it gave me low IDE memory.

**Comment by ap-wtioit** [comment]
In PyCharm under `Help` > `Show Log in Files` you should be able to open the directory where PyCharm saves it's logs. When opening idea.log you should be able to find the stacktrace there. Your help is much appreciated.
